### ISSUE TITLE
Dock Expose behavior changes when I add new tabs

### ISSUE THREAD

**Issue by aubreypwd** [steventheworker/Dock-Expos--home#30]
When adding a new tab to a window (e.g., Finder or Terminal), clicking the Dock icon requires you to choose a window w/ Expose, even if there is only one window but it has multiple tabs. 

This is inconsistent with single-window applications that do not have multiple tabs, where clicking the Dock icon simply switches to the only window without showing Exposé.

Additionally, when using the hover method (which I personally dislike), a choice is always given using Expose, even if the app only contains one window, regardless of whether it has tabs or not.

To clarify, I believe the correct behavior when clicking the Dock icon is to switch directly to the single window if there is only one, regardless of whether it has multiple tabs.

[Screencast...](https://ff695b5dd2960f41cb75835a324f0804.r2.cloudflarestorage.com/drp-cl/164ad555-261c-4631-9223-f8c4c333bca2/dd102d02-3311-4164-baf6-3b6d19b9eed8/54a443fb-7a56-4ebe-894f-181e12b8a1e3.mov?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=fed7aac277aea51eca0c294ada409f61%2F20240723%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240723T203032Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=0f11ff43d880cc601e703e650eb8f0f5e62e87c4c936ec40ddc1ec194d464d10)

**Comment by aubreypwd** [comment]
I had an instance where Dock Expose started _after_ a window was restored with multiple tabs, and for the only window (terminal) with multiple tabs (2), it didn't present a choice. But as soon as I created a 3rd tab it started asking me to choose again.

Seems like creating a tab seems to trigger this behavior.

[Screencast...](https://a.supportally.com/v/6o6czq)

**Comment by steventheworker** [comment]
Yup I ended up just doing [what AltTab does](https://github.com/lwouis/alt-tab-macos/blob/97951e7e8e9a1ab480a53279cf0f08160de28301/src/logic/Windows.swift#L230), only difference I run that when a window is added/closed (instead of whenever there's a preview attempt).

**Comment by aubreypwd** [comment]
I see you closed it, no plans to change this behavior in the future?

**Comment by steventheworker** [comment]
Sorry should've mentioned I pushed a new update (v3.00.5). Let me know if it works or not, and I'll reopen the issue.

**Comment by aubreypwd** [comment]
![CleanShot 2024-08-08 at 15 25 06](https://github.com/user-attachments/assets/6515b381-a5ce-49ff-9050-518de6d7f798)

I keep opening it and it immediately dies.

**Comment by aubreypwd** [comment]
even re-added it in Privacy Settings for recording screen and accessibility add/remove

**Comment by aubreypwd** [comment]
Finally got it to start...

**Comment by aubreypwd** [comment]
[Still seeing the same behavior with `3.00.5`](https://share.cleanshot.com/6bVkty4Vq2ggVsZ90hWf)

**Comment by steventheworker** [comment]
Can you download AltTab and let me know if it lists the tabbed windows correctly? 

![ScreenHint - 8:10:24, 10:15:58 PM](https://github.com/user-attachments/assets/6f55cb0a-4320-4638-876c-f988357cf8d0)

**Comment by aubreypwd** [comment]
With "Show standard tabs as windows" disabled:

![CleanShot 2024-08-12 at 08 05 49](https://github.com/user-attachments/assets/300e20ab-7f32-4eae-a358-250ad4682ac1)

...I get the right behavior, Finder lists only once for (1) window w/ (2) tabs:

![CleanShot 2024-08-12 at 08 07 02](https://github.com/user-attachments/assets/6821f2f0-425b-45cd-97e4-256719ce9fe7)

---

With "Show standard tabs as windows" enabled, I do see two finder instances, one for each tab:

![CleanShot 2024-08-12 at 08 06 01](https://github.com/user-attachments/assets/1b7ba84f-ea1a-4fa3-be82-46d37920117a)
